            environment: '"dev"'
            app_name: '""'
            version: "1.0.0"
            EOF
            echo "Generated config.yaml:"
            cat config.yaml
            Updated: Mon Mar  3 09:49:05 UTC 2025
Updated timestamp: Tue Mar  4 05:27:52 UTC 2025
